Repository KaanKalmi/release-candidate, pull requests merged in 2025-01, with the labels that each got.

#12 Refactor component list/structure and other small issue fixes
  src/lib/atoms/Expand.svelte
  src/lib/atoms/Link.svelte
  src/lib/atoms/Loader.svelte
  src/lib/molecules/Heading.svelte
  src/lib/molecules/Program.svelte
  src/lib/molecules/Semester.svelte
  src/lib/molecules/SprintLink.svelte
  src/lib/organisms/ContentSemester.svelte
  src/lib/organisms/ContentSprint.svelte
  src/lib/organisms/Loader.svelte
  src/lib/organisms/Nav.svelte
  src/lib/organisms/Schedule.svelte
  src/lib/organisms/Semesters.svelte
  src/lib/organisms/Tasks.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/[semester]/+page.svelte
Labels: documentation, enhancement, Component

#13 Added blur animation
  src/lib/molecules/Semester.svelte
  src/lib/molecules/SprintLink.svelte
Labels: documentation, enhancement

#15 Schedule.svelte Agenda Responsive
  src/lib/molecules/Semester.svelte
  src/lib/organisms/Schedule.svelte
Labels: enhancement, Component

#16 Detail fixing (margins, paddings, whitespace)
  src/lib/molecules/Heading.svelte
  src/lib/molecules/Program.svelte
  src/lib/molecules/Semester.svelte
  src/lib/molecules/Topics.svelte
  src/lib/organisms/ContentSemester.svelte
  src/lib/organisms/ContentSprint.svelte
  src/lib/organisms/Nav.svelte
  src/lib/organisms/Schedule.svelte
  src/lib/organisms/Semesters.svelte
  src/routes/+layout.svelte
  src/routes/[semester]/+page.svelte
Labels: bug, Component

#21 StudentWork data + UIX
  src/lib/atoms/Star.svelte
  src/lib/molecules/StudentWork.svelte
  src/routes/[semester]/[sprint]/+page.svelte
Labels: enhancement, Component

#27 before and after blur to studentWork - small
  src/lib/molecules/StudentWork.svelte
Labels: documentation, Component

#28 Details fixing
  src/lib/molecules/Program.svelte
  src/lib/molecules/Semester.svelte
  src/lib/organisms/Nav.svelte
  src/lib/organisms/Schedule.svelte
  src/lib/organisms/Tasks.svelte
  src/routes/[semester]/[sprint]/+page.svelte
Labels: documentation, Component

#29 Details fixing
  src/lib/molecules/Program.svelte
  src/lib/molecules/SprintLink.svelte
  src/lib/molecules/StudentWork.svelte
  src/lib/organisms/ContentSprint.svelte
  src/lib/organisms/Footer.svelte
  src/lib/organisms/Schedule.svelte
  src/lib/organisms/Semesters.svelte
  src/lib/organisms/Tasks.svelte
  src/routes/[semester]/[sprint]/+page.svelte
Labels: documentation, enhancement
